const OrderStatus = {
  UNSYNCHRONIZED: 'UNSYNCHRONIZED',
  NEW: 'NEW',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FILLED: 'FILLED',
  CANCELED: 'CANCELED',
  PENDING_CANCEL: 'PENDING_CANCEL',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
}

module.exports = {
  OrderStatus
}
